DROP TABLE IF EXISTS Zone CASCADE;
DROP TABLE IF EXISTS Parking CASCADE;
DROP TABLE IF EXISTS PLace CASCADE;
DROP TABLE IF EXISTS Utilisateur CASCADE;
DROP TABLE IF EXISTS UtilisateurAbonne CASCADE;
DROP TABLE IF EXISTS Vehicule CASCADE;
DROP TABLE IF EXISTS Reservation CASCADE;
DROP TABLE IF EXISTS Transaction CASCADE;

DROP TYPE IF EXISTS EEmplacement;
DROP TYPE IF EXISTS EVehicule;
DROP TYPE IF EXISTS EPaiement;
DROP TYPE IF EXISTS EBorne;
DROP TYPE IF EXISTS EStatus;
DROP TYPE IF EXISTS ETransaction;
